objects/Auto_User_Inactive__mdt/Auto_User_Inactive__mdt.object-meta.xml
<CustomObject>
    <description>Deactivate the configured profile user after set number of days.</description>
    <label>Auto User Inactive</label>
    <pluralLabel>Auto Users Inactive</pluralLabel>
</CustomObject>

objects/Auto_User_Inactive__mdt/fields/From_Last_Login_Date__c.field-meta.xml
<CustomField>
    <fullName>From_Last_Login_Date__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this checkbox if the user has to be deactivated if user has not logged in for given number of days.</inlineHelpText>
    <label>From Last Login Date</label>
    <type>Checkbox</type>
</CustomField>

objects/Auto_User_Inactive__mdt/fields/Number_of_Days__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Days__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The number of days user can be deactivated.</description>
    <label>Number of Days</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Deactivation_Date__c.field-meta.xml
<CustomField>
    <fullName>Deactivation_Date__c</fullName>
    <inlineHelpText>The date on which user will get deactivated.</inlineHelpText>
    <label>Deactivation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/DeactivateUsersBatch.cls
public class DeactivateUsersBatch implements Database.Batchable<sObject>, Schedulable{

    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator('SELECT Id,Deactivation_Date__c,isActive,Profile.Name,LastLoginDate FROM User WHERE isActive = true');
    }

    public void execute(Database.BatchableContext bc, List<sObject> scope){
        Map<String, Auto_User_Inactive__mdt> profileAUIMap = new Map<String, Auto_User_Inactive__mdt>();
        
        for(Auto_User_Inactive__mdt auI : [SELECT Label, Number_of_Days__c, From_Last_Login_Date__c FROM Auto_User_Inactive__mdt]){
            profileAUIMap.put(auI.Label, auI);
        }
        
        List<User> deactivatedUsers = new List<User>();
        User userRecord;
        for(sobject s : scope){
            userRecord = (User)s;
            if(profileAUIMap.containsKey(userRecord.Profile.Name)){
                if(!profileAUIMap.get(userRecord.Profile.Name).From_Last_Login_Date__c && userRecord.Deactivation_Date__c < Date.today()){
                    userRecord.isActive = false;
                    deactivatedUsers.add(userRecord);
                }else if(profileAUIMap.get(userRecord.Profile.Name).From_Last_Login_Date__c 
                    && (userRecord.LastLoginDate == null || 
                        userRecord.LastLoginDate < Date.today().addDays((Integer)profileAUIMap.get(userRecord.Profile.Name).Number_of_Days__c))){
                    userRecord.isActive = false;
                    deactivatedUsers.add(userRecord);
                }
            }
        }
        Database.update(deactivatedUsers, false);
    }
    
    public void execute(SchedulableContext ctx) {
        Database.executeBatch(new DeactivateUsersBatch(), 200);
    }

    public void finish(Database.BatchableContext bc){
    }
}